### ISSUE TITLE
Upgrade to Metamodel Version 3.0.RC02

### ISSUE THREAD

**Issue by sebbader-sap** [eclipse-aas4j/aas4j-model-generator#3]

**Comment by sebbader-sap** [comment]
@FrankSchnicke I just realise that the commit histories of the `main` here and my local version are completely different. Do you have any idea how to merge them?

**Comment by sebbader-sap** [comment]
Same problem applies for the fix for #4 as both are in the branch `feature/update-to-3.0.RC02`.

**Comment by FrankSchnicke** [comment]
I think the most sensible way is to add this repository as additional remote and then cherry-pick your changes as described here:
https://stackoverflow.com/a/5120074
