### ISSUE TITLE
Change Package Structure of the Output Library according to the Eclipse Project Pattern

### ISSUE THREAD

**Issue by sebbader-sap** [eclipse-aas4j/aas4j-model-generator#4]
old: io.adminshell.aas
new: org.eclipse.aas4j...

**Comment by twebermartins** [comment]
Please change path to:

groupID: `org.eclipse.digitaltwin.aas4j`

as agreed within Eclipse DT TPL PMC.

See also [Issue #19 ](https://github.com/eclipse-aas4j/aas4j/issues/19)

**Comment by sebbader-sap** [comment]
PR for this issue: https://github.com/eclipse-aas4j/aas4j/pull/42

**Comment by twebermartins** [comment]
> PR for this issue: [eclipse-aas4j/aas4j#42](https://github.com/eclipse-aas4j/aas4j/pull/42)

Looks fine to me! We can close the issue once we merge your PR?

**Comment by sebbader-sap** [comment]
Closing as PR has been approved and merged.
