### ISSUE TITLE
Remove wildcards in imports

### ISSUE THREAD

**Issue by sebbader** [eclipse-aas4j/aas4j-model-generator#7]
from https://github.com/admin-shell-io/java-generator/issues/11

Task: avoid lines like these:
```
import org.eclipse.aas4j.v3.model.builder.*;
import org.eclipse.aas4j.v3.model.impl.*;
```

**Comment by sebbader** [comment]
See https://github.com/admin-shell-io/java-generator/pull/4/files

**Comment by sebbader-sap** [comment]
Can be done via the Intellij "optimise input" feature.
